
package ocs2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OneCService2", targetNamespace = "http://OneCService2")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OneCService2 {


    /**
     * 
     * @param request
     * @param poolPassword
     * @param connectionName
     * @param poolUserName
     * @return
     *     returns ocs2.ResultSet
     */
    @WebMethod(operationName = "ExecuteRequest", action = "http://OneCService2/OneCService2/ExecuteRequest")
    @WebResult(name = "ExecuteRequestResult", targetNamespace = "http://OneCService2")
    @RequestWrapper(localName = "ExecuteRequest", targetNamespace = "http://OneCService2", className = "ocs2.ExecuteRequest")
    @ResponseWrapper(localName = "ExecuteRequestResponse", targetNamespace = "http://OneCService2", className = "ocs2.ExecuteRequestResponse")
    public ResultSet executeRequest(
        @WebParam(name = "_connectionName", targetNamespace = "http://OneCService2")
        String connectionName,
        @WebParam(name = "_poolUserName", targetNamespace = "http://OneCService2")
        String poolUserName,
        @WebParam(name = "_poolPassword", targetNamespace = "http://OneCService2")
        String poolPassword,
        @WebParam(name = "_request", targetNamespace = "http://OneCService2")
        String request);

    /**
     * 
     * @param poolPassword
     * @param script
     * @param connectionName
     * @param poolUserName
     * @return
     *     returns ocs2.ResultSet
     */
    @WebMethod(operationName = "ExecuteScript", action = "http://OneCService2/OneCService2/ExecuteScript")
    @WebResult(name = "ExecuteScriptResult", targetNamespace = "http://OneCService2")
    @RequestWrapper(localName = "ExecuteScript", targetNamespace = "http://OneCService2", className = "ocs2.ExecuteScript")
    @ResponseWrapper(localName = "ExecuteScriptResponse", targetNamespace = "http://OneCService2", className = "ocs2.ExecuteScriptResponse")
    public ResultSet executeScript(
        @WebParam(name = "_connectionName", targetNamespace = "http://OneCService2")
        String connectionName,
        @WebParam(name = "_poolUserName", targetNamespace = "http://OneCService2")
        String poolUserName,
        @WebParam(name = "_poolPassword", targetNamespace = "http://OneCService2")
        String poolPassword,
        @WebParam(name = "_script", targetNamespace = "http://OneCService2")
        String script);

    /**
     * 
     * @param poolPassword
     * @param parameters
     * @param methodName
     * @param connectionName
     * @param poolUserName
     * @return
     *     returns ocs2.ResultSet
     */
    @WebMethod(operationName = "ExecuteMethod", action = "http://OneCService2/OneCService2/ExecuteMethod")
    @WebResult(name = "ExecuteMethodResult", targetNamespace = "http://OneCService2")
    @RequestWrapper(localName = "ExecuteMethod", targetNamespace = "http://OneCService2", className = "ocs2.ExecuteMethod")
    @ResponseWrapper(localName = "ExecuteMethodResponse", targetNamespace = "http://OneCService2", className = "ocs2.ExecuteMethodResponse")
    public ResultSet executeMethod(
        @WebParam(name = "_connectionName", targetNamespace = "http://OneCService2")
        String connectionName,
        @WebParam(name = "_poolUserName", targetNamespace = "http://OneCService2")
        String poolUserName,
        @WebParam(name = "_poolPassword", targetNamespace = "http://OneCService2")
        String poolPassword,
        @WebParam(name = "_methodName", targetNamespace = "http://OneCService2")
        String methodName,
        @WebParam(name = "_parameters", targetNamespace = "http://OneCService2")
        Parameters parameters);

}
