<?xml version="1.0" encoding="UTF-8"?>
<definitions name="TestExecuteScript" targetNamespace="http://j2ee.netbeans.org/wsdl/TestBPEL/TestExecuteScript"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/TestBPEL/TestExecuteScript" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="ExecuteScriptRequest">
        <part name="script" type="xsd:string"/>
    </message>
    <message name="ExecuteScriptResponse">
        <part name="resultSet" type="xsd:anyType"/>
    </message>
    <portType name="TestExecuteScriptPortType">
        <operation name="ExecuteScript">
            <input name="input1" message="tns:ExecuteScriptRequest"/>
            <output name="output1" message="tns:ExecuteScriptResponse"/>
        </operation>
    </portType>
    <binding name="TestExecuteScriptBinding" type="tns:TestExecuteScriptPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="ExecuteScript">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/TestBPEL/TestExecuteScript"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/TestBPEL/TestExecuteScript"/>
            </output>
        </operation>
    </binding>
    <service name="TestExecuteScriptService">
        <port name="TestExecuteScriptPort" binding="tns:TestExecuteScriptBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/TestExecuteScriptService/TestExecuteScriptPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="TestExecuteScript">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="TestExecuteScriptPortTypeRole" portType="tns:TestExecuteScriptPortType"/>
    </plnk:partnerLinkType>
</definitions>
